language: node_js

node_js:
    - "node"
    - "10"
    - "8"

sudo: false

git:
    submodules: false

before_script:
    - chmod +x db/reset_test_db.bash
    - npm install
env:
    JWT_SECRET='thisIsNoSecret'

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov